PRED_KEY_SEMANTIC = 'semantic'
GT_KEY_SEMANTIC = 'semantic'
PRED_KEY_INSTANCE_CENTER = 'instance_center'
GT_KEY_INSTANCE_CENTER = 'instance_center'
PRED_KEY_CENTER_REGRESSION = 'center_regression'
GT_KEY_CENTER_REGRESSION = 'center_regression'
